# Generated by Django 5.1.4 on 2024-12-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assignDate', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='taskcategories.taskcategory')),
            ],
        ),
    ]
